// ============================================
// PathRAG Diagnostic Nodes
// TP-Link Router Diagnostic Path (Primary)
// ============================================

import { DiagnosticNode, DiagnosticPhase } from './types';

export const DIAGNOSTIC_NODES: DiagnosticNode[] = [
  // ========================================
  // PHASE 0 - Entry & Context Setup
  // ========================================
  {
    node_id: 'entry_start',
    phase: DiagnosticPhase.ENTRY,
    input_type: 'confirmation',
    question: 'Ready to begin router diagnosis?',
    voice_instruction: "Hi! I'm Akili. I'll help fix your internet. Ready to start?",
    allowed_assets: ['intro_diagram'],
    expected_answers: {
      'yes': 'entry_router_identify',
      'ready': 'entry_router_identify',
      'sure': 'entry_router_identify',
      'ok': 'entry_router_identify',
      'okay': 'entry_router_identify',
      'no': 'entry_postpone',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'entry_router_identify',
    phase: DiagnosticPhase.ENTRY,
    input_type: 'user_observation',
    question: 'What brand is your router?',
    voice_instruction: "What brand is your router? Look at the front for the name - is it TP-Link, Netgear, D-Link, or something else?",
    allowed_assets: ['router_brands_guide', 'tplink_mr600_physical_setup'],
    expected_answers: {
      'tplink': 'physical_power_led',
      'tp-link': 'physical_power_led',
      'tp link': 'physical_power_led',
      'mr600': 'physical_power_led',
      'archer': 'physical_power_led',
      'netgear': 'physical_power_led',
      'dlink': 'physical_power_led',
      'd-link': 'physical_power_led',
      'asus': 'physical_power_led',
      'other': 'physical_power_led',
      'generic': 'physical_power_led',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'entry_postpone',
    phase: DiagnosticPhase.ENTRY,
    input_type: 'confirmation',
    question: 'Would you like to continue later?',
    voice_instruction: "No problem! When you're ready, just say 'start diagnosis' and we can begin. Is there anything else I can help clarify before we end?",
    allowed_assets: [],
    expected_answers: {
      'yes': 'session_end',
      'no': 'entry_start',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },

  // ========================================
  // PHASE 1 - Physical Layer Verification
  // ========================================
  {
    node_id: 'physical_power_led',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_observation',
    question: 'What color is the power LED?',
    voice_instruction: "Look at the front of your router. The Power light is on the left side. On TP-Link MR600, the lights are WHITE when on. Is the power light on, blinking, or off?",
    allowed_assets: ['tplink_mr600_led_layout', 'led_power_guide'],
    expected_answers: {
      'on': 'physical_internet_led',
      'white': 'physical_internet_led',
      'solid': 'physical_internet_led',
      'green': 'physical_internet_led',
      'solid green': 'physical_internet_led',
      'orange': 'physical_power_issue',
      'amber': 'physical_power_issue',
      'blinking': 'physical_power_booting',
      'off': 'physical_power_off',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
      screen_mismatch: true,
      max_retries: 3,
    },
  },
  {
    node_id: 'physical_power_off',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_action',
    question: 'Is the router plugged in?',
    voice_instruction: "The power light is off. Let's check the basics. First, confirm the power cable is firmly plugged into the back of the router. Then check that the other end is plugged into a working power outlet. Once you've checked both connections, tell me - is everything plugged in?",
    allowed_assets: ['power_cable_guide'],
    expected_answers: {
      'yes': 'physical_power_led_recheck',
      'plugged in': 'physical_power_led_recheck',
      'no': 'physical_power_reconnect',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      user_uncertain: true,
      retry_exceeded: true,
      max_retries: 2,
    },
  },
  {
    node_id: 'physical_power_reconnect',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_action',
    question: 'Please plug in the power cable',
    voice_instruction: "Please plug the power cable into the router and into a working outlet. Let me know when it's plugged in and any lights come on.",
    allowed_assets: ['power_cable_guide'],
    expected_answers: {
      'done': 'physical_power_led_recheck',
      'plugged in': 'physical_power_led_recheck',
      'yes': 'physical_power_led_recheck',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      user_uncertain: true,
      max_retries: 2,
    },
  },
  {
    node_id: 'physical_power_led_recheck',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_observation',
    question: 'What color is the power LED now?',
    voice_instruction: "Now look at the power light again. What color is it showing now - green, orange, blinking, or still off?",
    allowed_assets: ['led_power_guide'],
    expected_answers: {
      'green': 'physical_internet_led',
      'solid green': 'physical_internet_led',
      'orange': 'physical_power_issue',
      'blinking': 'physical_power_booting',
      'off': 'escalation_hardware',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'physical_power_issue',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_action',
    question: 'Router may have hardware issue',
    voice_instruction: "An orange power light usually indicates a hardware problem or the router is in recovery mode. Let's try a power cycle. Unplug the power cable, wait 10 seconds, then plug it back in. Tell me when you've done that.",
    allowed_assets: ['power_cycle_guide'],
    expected_answers: {
      'done': 'physical_power_led_recheck',
      'yes': 'physical_power_led_recheck',
    },
    actions_allowed: ['POWER_CYCLE'],
    escalation_conditions: {
      retry_exceeded: true,
      max_retries: 2,
    },
  },
  {
    node_id: 'physical_power_booting',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_observation',
    question: 'Router is booting, please wait',
    voice_instruction: "The router is starting up - that's normal for a blinking light. Let's wait about 60 seconds for it to fully boot. Watch the power light and tell me when it becomes steady green.",
    allowed_assets: ['led_power_guide'],
    expected_answers: {
      'green': 'physical_internet_led',
      'solid green': 'physical_internet_led',
      'still blinking': 'physical_power_issue',
      'orange': 'physical_power_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 3,
    },
  },
  {
    node_id: 'physical_internet_led',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_observation',
    question: 'What is the Internet LED doing?',
    voice_instruction: "Now look at the Internet light - it's the second light from the left. On TP-Link MR600 it will be WHITE when connected. Is it on, blinking, or off?",
    allowed_assets: ['tplink_mr600_led_layout', 'led_internet_guide'],
    expected_answers: {
      'on': 'local_network_check',
      'white': 'local_network_check',
      'solid': 'local_network_check',
      'green': 'local_network_check',
      'solid green': 'local_network_check',
      'orange': 'physical_wan_cable_check',
      'red': 'physical_wan_cable_check',
      'blinking': 'physical_wan_connecting',
      'off': 'physical_wan_cable_check',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
      max_retries: 3,
    },
  },
  {
    node_id: 'physical_wan_cable_check',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_action',
    question: 'Check WAN cable connection',
    voice_instruction: "The internet light suggests a connection problem. Look at the back of your router for a port labeled 'WAN' or 'Internet' - it's usually a different color, often blue or yellow. Check if there's a cable plugged in there. Is a cable connected to that port?",
    allowed_assets: ['wan_port_guide', 'cable_check_diagram'],
    expected_answers: {
      'yes': 'physical_wan_reseat',
      'connected': 'physical_wan_reseat',
      'no': 'physical_wan_connect',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'physical_wan_connect',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_action',
    question: 'Connect the WAN cable',
    voice_instruction: "You'll need to connect the cable from your modem or ONT box to the WAN port on your router. The cable should click in securely. Let me know when it's connected.",
    allowed_assets: ['wan_port_guide', 'ont_connection_diagram'],
    expected_answers: {
      'done': 'physical_internet_led_recheck',
      'connected': 'physical_internet_led_recheck',
      'yes': 'physical_internet_led_recheck',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'physical_wan_reseat',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_action',
    question: 'Reseat the WAN cable',
    voice_instruction: "Let's reseat that cable. Unplug the cable from the WAN port, wait 5 seconds, then firmly plug it back in until you hear a click. Also check the other end where it connects to your modem. Tell me when done.",
    allowed_assets: ['cable_reseat_guide'],
    expected_answers: {
      'done': 'physical_internet_led_recheck',
      'yes': 'physical_internet_led_recheck',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'physical_wan_connecting',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_observation',
    question: 'WAN is attempting to connect',
    voice_instruction: "A blinking internet light means the router is trying to establish a connection. Let's wait 30 seconds. Watch the light - does it become solid green, or does it stay blinking or go orange?",
    allowed_assets: ['led_internet_guide'],
    expected_answers: {
      'green': 'local_network_check',
      'solid green': 'local_network_check',
      'still blinking': 'physical_wan_cable_check',
      'orange': 'physical_wan_cable_check',
      'red': 'physical_wan_cable_check',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 3,
    },
  },
  {
    node_id: 'physical_internet_led_recheck',
    phase: DiagnosticPhase.PHYSICAL_LAYER,
    input_type: 'user_observation',
    question: 'What color is the Internet LED now?',
    voice_instruction: "Look at the Internet light again. What color is it showing now?",
    allowed_assets: ['led_internet_guide'],
    expected_answers: {
      'green': 'local_network_check',
      'solid green': 'local_network_check',
      'orange': 'wan_status_check',
      'red': 'wan_status_check',
      'blinking': 'physical_wan_connecting',
      'off': 'escalation_wan_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },

  // ========================================
  // PHASE 2 - Local Network Sanity Check
  // ========================================
  {
    node_id: 'local_network_check',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_observation',
    question: 'How are you connected to the router?',
    voice_instruction: "The router looks healthy. Now let's check your device's connection. Are you connected to the router via WiFi or with an ethernet cable plugged directly in?",
    allowed_assets: ['connection_types_guide'],
    expected_answers: {
      'wifi': 'local_wifi_connected',
      'wireless': 'local_wifi_connected',
      'ethernet': 'local_ethernet_check',
      'cable': 'local_ethernet_check',
      'wired': 'local_ethernet_check',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'local_wifi_connected',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_observation',
    question: 'Is WiFi showing connected?',
    voice_instruction: "On your phone or computer, look at the WiFi icon in the corner of your screen. Does it show you're connected to your WiFi network? You should see the network name.",
    allowed_assets: ['wifi_icon_guide'],
    expected_answers: {
      'yes': 'local_browser_test',
      'connected': 'local_browser_test',
      'no': 'local_wifi_reconnect',
      'disconnected': 'local_wifi_reconnect',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'local_wifi_reconnect',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_action',
    question: 'Connect to WiFi network',
    voice_instruction: "Let's connect to your WiFi. Go to your WiFi settings, find your network name, and connect. You'll need your WiFi password. Let me know when you're connected.",
    allowed_assets: ['wifi_connect_guide'],
    expected_answers: {
      'connected': 'local_browser_test',
      'done': 'local_browser_test',
      'yes': 'local_browser_test',
      'failed': 'escalation_wifi_issue',
      "can't connect": 'escalation_wifi_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
      max_retries: 3,
    },
  },
  {
    node_id: 'local_ethernet_check',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_observation',
    question: 'Is ethernet cable securely connected?',
    voice_instruction: "Check the ethernet cable is firmly connected at both ends - one end in your computer, the other in one of the numbered LAN ports on the router (not the WAN port). Are both ends secure?",
    allowed_assets: ['ethernet_connection_guide'],
    expected_answers: {
      'yes': 'local_browser_test',
      'secure': 'local_browser_test',
      'no': 'local_ethernet_reseat',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'local_ethernet_reseat',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_action',
    question: 'Reseat ethernet cable',
    voice_instruction: "Please firmly connect the ethernet cable at both ends. You should hear a click when it's properly seated. Let me know when done.",
    allowed_assets: ['ethernet_connection_guide'],
    expected_answers: {
      'done': 'local_browser_test',
      'yes': 'local_browser_test',
    },
    actions_allowed: ['RESEAT_CABLE'],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'local_browser_test',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_action',
    question: 'Can you access the router admin page?',
    voice_instruction: "Open a web browser and type tplinkmodem.net in the address bar. Press Enter. Do you see a login page?",
    allowed_assets: ['tplink_mr600_addressbar', 'tplink_mr600_login'],
    expected_answers: {
      'yes': 'router_login_prompt',
      'see it': 'router_login_prompt',
      'login page': 'router_login_prompt',
      'no': 'local_gateway_alt',
      "can't access": 'local_gateway_alt',
      'error': 'local_gateway_alt',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
      screen_mismatch: true,
    },
  },
  {
    node_id: 'local_gateway_alt',
    phase: DiagnosticPhase.LOCAL_NETWORK,
    input_type: 'user_action',
    question: 'Try alternate gateway address',
    voice_instruction: "Let's try a different address. Type 192.168.0.1 in the address bar instead. Some TP-Link models use this address. Do you see the router page now?",
    allowed_assets: ['browser_address_guide'],
    expected_answers: {
      'yes': 'router_login_prompt',
      'see it': 'router_login_prompt',
      'no': 'escalation_access_issue',
      "can't access": 'escalation_access_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      screen_mismatch: true,
      max_retries: 2,
    },
  },

  // ========================================
  // PHASE 3 - Router Login & Navigation
  // ========================================
  {
    node_id: 'router_login_prompt',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_action',
    question: 'Login to the router',
    voice_instruction: "Enter the password. Check the sticker on the bottom of your router for the default password. Did you get in?",
    allowed_assets: ['tplink_mr600_login', 'default_credentials_guide'],
    expected_answers: {
      'yes': 'router_dashboard_confirm',
      'logged in': 'router_dashboard_confirm',
      "in": 'router_dashboard_confirm',
      'no': 'router_login_failed',
      "can't login": 'router_login_failed',
      'wrong password': 'router_login_failed',
    },
    actions_allowed: ['RESET_CREDENTIALS'],
    escalation_conditions: {
      user_uncertain: true,
      max_retries: 3,
    },
  },
  {
    node_id: 'router_login_failed',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_observation',
    question: 'Check for password on router',
    voice_instruction: "The default password may have been changed. Look at the bottom or back of your router for a sticker with login details. Do you see any credentials printed there?",
    allowed_assets: ['router_sticker_guide'],
    expected_answers: {
      'yes': 'router_login_retry',
      'found it': 'router_login_retry',
      'no': 'router_factory_reset_offer',
      'nothing': 'router_factory_reset_offer',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'router_login_retry',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_action',
    question: 'Try credentials from sticker',
    voice_instruction: "Try logging in with the username and password from the sticker. Let me know if you get in.",
    allowed_assets: ['router_login_tplink'],
    expected_answers: {
      'yes': 'router_dashboard_confirm',
      'logged in': 'router_dashboard_confirm',
      'in': 'router_dashboard_confirm',
      'no': 'router_factory_reset_offer',
      'failed': 'router_factory_reset_offer',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'router_factory_reset_offer',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'confirmation',
    question: 'Would you like to factory reset the router?',
    voice_instruction: "We can't log in with the available credentials. I can guide you through a factory reset using the small reset button on your router. This will erase custom settings like your WiFi name and password, but it will restore the default login. Would you like to proceed with a factory reset?",
    allowed_assets: ['factory_reset_guide'],
    expected_answers: {
      'yes': 'router_factory_reset_locate',
      'ok': 'router_factory_reset_locate',
      'proceed': 'router_factory_reset_locate',
      'no': 'escalation_login_issue',
      'skip': 'escalation_login_issue',
    },
    actions_allowed: ['FACTORY_RESET'],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'router_factory_reset_locate',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_observation',
    question: 'Find the reset button',
    voice_instruction: "Look at the back of your router for a tiny pinhole labeled Reset. You'll need a paperclip to press it. Have you found it?",
    allowed_assets: ['tplink_mr600_reset_button', 'tplink_mr600_back_panel'],
    expected_answers: {
      'yes': 'router_factory_reset_execute',
      'found it': 'router_factory_reset_execute',
      'see it': 'router_factory_reset_execute',
      'no': 'router_factory_reset_help',
      "can't find": 'router_factory_reset_help',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'router_factory_reset_help',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_observation',
    question: 'Check all sides of router',
    voice_instruction: "The reset button is often hidden. Check the back panel near the ports, or sometimes it's on the bottom. It's a tiny pinhole, not a regular button. Look carefully at all sides. Have you found it now?",
    allowed_assets: ['factory_reset_guide'],
    expected_answers: {
      'yes': 'router_factory_reset_execute',
      'found it': 'router_factory_reset_execute',
      'no': 'escalation_login_issue',
      "can't find": 'escalation_login_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'router_factory_reset_execute',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_action',
    question: 'Perform the factory reset',
    voice_instruction: "Insert your paperclip or pin into the reset hole. Press and hold the button firmly for about 10 to 15 seconds. You should see the lights on the router blink or all turn off, then come back on. Keep holding until the lights flash. Let me know when the lights start blinking.",
    allowed_assets: ['factory_reset_guide'],
    expected_answers: {
      'done': 'router_factory_reset_wait',
      'blinking': 'router_factory_reset_wait',
      'lights flashed': 'router_factory_reset_wait',
      'yes': 'router_factory_reset_wait',
    },
    actions_allowed: ['FACTORY_RESET'],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'router_factory_reset_wait',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_observation',
    question: 'Wait for router to restart',
    voice_instruction: "The router is now resetting. This takes about 2 to 3 minutes. Wait until all the lights become steady again - especially the power light should be solid green. Let me know when the router seems fully restarted.",
    allowed_assets: ['led_power_guide'],
    expected_answers: {
      'done': 'router_factory_reset_reconnect',
      'ready': 'router_factory_reset_reconnect',
      'yes': 'router_factory_reset_reconnect',
      'lights steady': 'router_factory_reset_reconnect',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 3,
    },
  },
  {
    node_id: 'router_factory_reset_reconnect',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_action',
    question: 'Reconnect to the router',
    voice_instruction: "The router has been reset. Your WiFi network name is now back to the default - check the sticker on the router for the default WiFi name and password. Connect to that network, then try accessing the router page at 192.168.0.1 again. Let me know when you see the login page.",
    allowed_assets: ['router_login_tplink', 'router_sticker_guide'],
    expected_answers: {
      'yes': 'router_factory_reset_login',
      'see it': 'router_factory_reset_login',
      'done': 'router_factory_reset_login',
      'no': 'local_gateway_alt',
      "can't connect": 'local_wifi_reconnect',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'router_factory_reset_login',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_action',
    question: 'Login with default credentials',
    voice_instruction: "Now try logging in with the default credentials. The username is usually 'admin' and the password is either 'admin', 'password', or printed on the router sticker. Did you get in?",
    allowed_assets: ['router_login_tplink', 'default_credentials_guide'],
    expected_answers: {
      'yes': 'router_dashboard_confirm',
      'logged in': 'router_dashboard_confirm',
      'in': 'router_dashboard_confirm',
      'no': 'escalation_login_issue',
      'failed': 'escalation_login_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'router_dashboard_confirm',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_observation',
    question: 'Can you see the router dashboard?',
    voice_instruction: "Do you see the main dashboard with the network map and internet status?",
    allowed_assets: ['tplink_mr600_dashboard'],
    expected_answers: {
      'yes': 'wan_status_check',
      'see it': 'wan_status_check',
      'no': 'router_navigate_status',
      'different': 'router_navigate_status',
    },
    actions_allowed: [],
    escalation_conditions: {
      screen_mismatch: true,
    },
  },
  {
    node_id: 'router_navigate_status',
    phase: DiagnosticPhase.ROUTER_LOGIN,
    input_type: 'user_action',
    question: 'Navigate to status page',
    voice_instruction: "Look for a menu item called 'Status', 'Network Status', or 'Internet' in the navigation. It might be in a sidebar on the left or tabs at the top. Click on it to see your connection status.",
    allowed_assets: ['tplink_navigation_guide'],
    expected_answers: {
      'found it': 'wan_status_check',
      'yes': 'wan_status_check',
      'done': 'wan_status_check',
      "can't find": 'escalation_ui_mismatch',
    },
    actions_allowed: [],
    escalation_conditions: {
      screen_mismatch: true,
      user_uncertain: true,
    },
  },

  // ========================================
  // PHASE 4 - WAN / Internet Status Inspection
  // ========================================
  {
    node_id: 'wan_status_check',
    phase: DiagnosticPhase.WAN_INSPECTION,
    input_type: 'user_observation',
    question: 'What is the WAN/Internet connection status?',
    voice_instruction: "On the status page, look for 'WAN' or 'Internet' connection status. It should show if you're connected or disconnected, and might display an IP address. What does it say - Connected, Disconnected, or something else?",
    allowed_assets: ['wan_status_connected', 'wan_status_disconnected'],
    expected_answers: {
      'connected': 'wan_ip_check',
      'online': 'wan_ip_check',
      'disconnected': 'action_reconnect_wan',
      'offline': 'action_reconnect_wan',
      'connecting': 'wan_status_wait',
      'no ip': 'action_reconnect_wan',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
      screen_mismatch: true,
    },
  },
  {
    node_id: 'wan_status_wait',
    phase: DiagnosticPhase.WAN_INSPECTION,
    input_type: 'user_observation',
    question: 'Wait for connection to establish',
    voice_instruction: "The router is trying to connect. Let's wait 30 seconds. Watch the status - does it change to Connected, or does it show an error?",
    allowed_assets: ['wan_status_connecting'],
    expected_answers: {
      'connected': 'wan_ip_check',
      'disconnected': 'action_reconnect_wan',
      'error': 'action_reconnect_wan',
      'still connecting': 'action_reconnect_wan',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 3,
    },
  },
  {
    node_id: 'wan_ip_check',
    phase: DiagnosticPhase.WAN_INSPECTION,
    input_type: 'user_observation',
    question: 'Do you see a WAN IP address?',
    voice_instruction: "Look for 'IP Address' or 'WAN IP' on this page. It should show numbers like 123.45.67.89. Do you see an IP address, or does it show 0.0.0.0 or blank?",
    allowed_assets: ['wan_ip_guide'],
    expected_answers: {
      'yes': 'verification_internet_test',
      'see ip': 'verification_internet_test',
      'has ip': 'verification_internet_test',
      'no': 'action_reconnect_wan',
      '0.0.0.0': 'action_reconnect_wan',
      'blank': 'action_reconnect_wan',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },

  // ========================================
  // PHASE 5 - Guided Corrective Actions
  // ========================================
  {
    node_id: 'action_reconnect_wan',
    phase: DiagnosticPhase.CORRECTIVE_ACTIONS,
    input_type: 'user_action',
    question: 'Reconnect WAN connection',
    voice_instruction: "Let's try reconnecting. Look for a 'Connect' or 'Reconnect' button near the WAN status. If you see one, click it. Otherwise, look for 'Save' or 'Apply' button. Let me know when you've clicked it.",
    allowed_assets: ['wan_reconnect_guide'],
    expected_answers: {
      'done': 'action_wait_reconnect',
      'clicked': 'action_wait_reconnect',
      'yes': 'action_wait_reconnect',
      "can't find": 'action_reboot_router',
    },
    actions_allowed: ['RECONNECT_SESSION', 'SAVE_APPLY'],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'action_wait_reconnect',
    phase: DiagnosticPhase.CORRECTIVE_ACTIONS,
    input_type: 'user_observation',
    question: 'Wait for reconnection',
    voice_instruction: "Wait about 30 seconds for the router to reconnect. Watch the WAN status - does it change to Connected with an IP address?",
    allowed_assets: ['wan_status_connected'],
    expected_answers: {
      'connected': 'verification_internet_test',
      'yes': 'verification_internet_test',
      'has ip': 'verification_internet_test',
      'still disconnected': 'action_reboot_router',
      'no': 'action_reboot_router',
      'failed': 'action_reboot_router',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'action_reboot_router',
    phase: DiagnosticPhase.CORRECTIVE_ACTIONS,
    input_type: 'user_action',
    question: 'Reboot the router',
    voice_instruction: "Let's try a soft reboot. In the router interface, look for 'System Tools', 'Administration', or 'Management' in the menu. Then find 'Reboot' or 'Restart'. Click it and confirm. The router will restart - this takes about 2 minutes.",
    allowed_assets: ['reboot_guide', 'tplink_system_tools'],
    expected_answers: {
      'done': 'action_reboot_wait',
      'rebooting': 'action_reboot_wait',
      'yes': 'action_reboot_wait',
      "can't find": 'action_power_cycle',
    },
    actions_allowed: ['SOFT_REBOOT'],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'action_power_cycle',
    phase: DiagnosticPhase.CORRECTIVE_ACTIONS,
    input_type: 'user_action',
    question: 'Power cycle the router',
    voice_instruction: "Let's do a manual power cycle. Unplug the router's power cable, wait 30 seconds, then plug it back in. Wait for all the lights to come back on. Let me know when the router is fully restarted.",
    allowed_assets: ['power_cycle_guide'],
    expected_answers: {
      'done': 'action_reboot_wait',
      'yes': 'action_reboot_wait',
      'back on': 'action_reboot_wait',
    },
    actions_allowed: ['POWER_CYCLE'],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'action_reboot_wait',
    phase: DiagnosticPhase.CORRECTIVE_ACTIONS,
    input_type: 'user_observation',
    question: 'Wait for router to restart',
    voice_instruction: "The router is restarting. Wait until you see all lights steady, then try accessing the router page again at 192.168.0.1. Let me know when you can access it.",
    allowed_assets: ['router_login_tplink'],
    expected_answers: {
      'yes': 'verification_wan_recheck',
      'done': 'verification_wan_recheck',
      'can access': 'verification_wan_recheck',
      'no': 'escalation_reboot_failed',
      "can't access": 'escalation_reboot_failed',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 3,
    },
  },

  // ========================================
  // PHASE 6 - Verification
  // ========================================
  {
    node_id: 'verification_wan_recheck',
    phase: DiagnosticPhase.VERIFICATION,
    input_type: 'user_observation',
    question: 'Check WAN status after reboot',
    voice_instruction: "After logging back in, check the WAN status again. Is it showing Connected with an IP address?",
    allowed_assets: ['wan_status_connected'],
    expected_answers: {
      'connected': 'verification_internet_test',
      'yes': 'verification_internet_test',
      'has ip': 'verification_internet_test',
      'disconnected': 'escalation_persistent_issue',
      'no': 'escalation_persistent_issue',
    },
    actions_allowed: [],
    escalation_conditions: {
      max_retries: 2,
    },
  },
  {
    node_id: 'verification_internet_test',
    phase: DiagnosticPhase.VERIFICATION,
    input_type: 'user_action',
    question: 'Test internet connection',
    voice_instruction: "Let's test if the internet is actually working. Open a new browser tab and try going to google.com. Does the Google page load?",
    allowed_assets: ['internet_test_guide'],
    expected_answers: {
      'yes': 'verification_complete',
      'works': 'verification_complete',
      'loaded': 'verification_complete',
      'no': 'verification_dns_test',
      "doesn't work": 'verification_dns_test',
      'error': 'verification_dns_test',
    },
    actions_allowed: [],
    escalation_conditions: {
      user_uncertain: true,
    },
  },
  {
    node_id: 'verification_dns_test',
    phase: DiagnosticPhase.VERIFICATION,
    input_type: 'user_action',
    question: 'Test with IP address',
    voice_instruction: "Let's try accessing a site directly by IP. Try going to 8.8.8.8 in your browser. This tests if the connection works without DNS. Does anything load?",
    allowed_assets: [],
    expected_answers: {
      'yes': 'escalation_dns_issue',
      'works': 'escalation_dns_issue',
      'no': 'escalation_connectivity_issue',
      "doesn't work": 'escalation_connectivity_issue',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'verification_complete',
    phase: DiagnosticPhase.VERIFICATION,
    input_type: 'confirmation',
    question: 'Issue resolved!',
    voice_instruction: "Excellent! Your internet connection is working now. The issue has been resolved. Is there anything else you'd like help with?",
    allowed_assets: ['success_diagram'],
    expected_answers: {
      'no': 'session_end',
      'done': 'session_end',
      'thank you': 'session_end',
      'yes': 'entry_start',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'session_end',
    phase: DiagnosticPhase.POST_SESSION,
    input_type: 'confirmation',
    question: 'Session complete',
    voice_instruction: "Thank you for contacting support. Your session is now complete. Have a great day!",
    allowed_assets: [],
    expected_answers: {},
    actions_allowed: [],
    escalation_conditions: {},
  },

  // ========================================
  // PHASE 7 - Escalation Nodes
  // ========================================
  {
    node_id: 'escalation_hardware',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'Hardware issue detected',
    voice_instruction: "It appears there may be a hardware issue with your router. The power light not coming on after checking connections suggests the router may need replacement. I recommend contacting your internet service provider or the router manufacturer for a hardware check.",
    allowed_assets: ['escalation_hardware_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_wan_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'WAN connection issue',
    voice_instruction: "We've tried the main troubleshooting steps but the WAN connection isn't establishing. This could indicate an issue with your modem, the line from your ISP, or your ISP's network. I recommend contacting your internet service provider to check for outages or line issues.",
    allowed_assets: ['escalation_isp_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_wifi_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'WiFi connection issue',
    voice_instruction: "There seems to be an issue connecting to the WiFi network. This might be a password problem or interference issue. Try connecting from a different device, or use an ethernet cable temporarily. If the problem persists, you may need to reset the WiFi settings on the router.",
    allowed_assets: ['escalation_wifi_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_access_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'Cannot access router',
    voice_instruction: "We're unable to access the router's admin page. This could mean the device isn't properly connected, or the router might need a factory reset. Alternatively, your device might have a different gateway address. I recommend checking your device's network settings or contacting support.",
    allowed_assets: ['escalation_access_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_login_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'Cannot login to router',
    voice_instruction: "Unfortunately, we weren't able to access the router's admin panel. You may need to contact your internet service provider for help, or if this is your own router, reach out to the manufacturer's support. They can help you regain access or replace the router if needed.",
    allowed_assets: ['escalation_support_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_ui_mismatch',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'Router UI does not match',
    voice_instruction: "The router interface looks different from what I expected. Your router may have a different firmware version or be a different model. Without being able to match the interface, I cannot guide you safely. I recommend checking your router's documentation or contacting technical support.",
    allowed_assets: [],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_reboot_failed',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'Router not responding after reboot',
    voice_instruction: "The router isn't responding after the restart. Try waiting a few more minutes - sometimes routers take longer to fully boot. If it still doesn't respond, there may be a hardware issue. Contact your ISP or router manufacturer for further assistance.",
    allowed_assets: [],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_persistent_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'Issue persists after troubleshooting',
    voice_instruction: "We've tried the main troubleshooting steps but the connection issue persists. This suggests a problem outside the router - likely with your modem, ISP service, or the line connection. Please contact your internet service provider to report the issue and request a line check.",
    allowed_assets: ['escalation_isp_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_dns_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'DNS resolution issue',
    voice_instruction: "Your internet connection is working, but there's a DNS problem - the service that translates website names to addresses. Try changing your DNS servers to Google DNS (8.8.8.8) or Cloudflare (1.1.1.1) in your router or device settings. This usually resolves the issue.",
    allowed_assets: ['dns_settings_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
  {
    node_id: 'escalation_connectivity_issue',
    phase: DiagnosticPhase.ESCALATION,
    input_type: 'confirmation',
    question: 'No internet connectivity',
    voice_instruction: "Even direct IP access isn't working, which confirms there's no internet connectivity through your router. The issue is likely with your modem, ISP service, or the physical line. Please contact your internet service provider to check for outages or line problems.",
    allowed_assets: ['escalation_isp_guide'],
    expected_answers: {
      'ok': 'session_end',
      'understood': 'session_end',
    },
    actions_allowed: [],
    escalation_conditions: {},
  },
];

// Helper function to get node by ID
export function getNodeById(nodeId: string): DiagnosticNode | null {
  return DIAGNOSTIC_NODES.find(n => n.node_id === nodeId) || null;
}

// Get all nodes for a specific phase
export function getNodesForPhase(phase: DiagnosticPhase): DiagnosticNode[] {
  return DIAGNOSTIC_NODES.filter(n => n.phase === phase);
}

// Get the entry node
export function getEntryNode(): DiagnosticNode {
  return DIAGNOSTIC_NODES.find(n => n.node_id === 'entry_start')!;
}
